dir: /Users/nbrenny/Documents/fun/mls/url/2024-11-26/
outfile: 2024-11-26.json
saved_match_list_json: /Users/nbrenny/Documents/fun/mls/url/2024-11-26//2024-11-26.json
url: https://www.mlssoccer.com/schedule/scores#competition=all&club=all&date=2024-11-26
wait_time: 5
