dir: /Users/nbrenny/Documents/fun/mls/url/2024-10-18/
outfile: match_list.json
saved_match_list_json: /Users/nbrenny/Documents/fun/mls/url/2024-10-18//match_list.json
url: https://www.mlssoccer.com/schedule/scores#competition=all&club=all&date=2024-10-18
wait_time: 5
